import Head from 'next/head'
import { tw } from 'twind'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={tw`w-[100vw] h-full bg-[url('public/Image/Back.svg')]`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      </main>


    </div>
  )
}
