import Head from 'next/head'
import { tw, css } from 'twind/css'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={tw`flex flex-1 w-full h-full min-h-[100vh] ${css({backgroundImage : "url('/images/back.svg')"})}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


    </div>
  )
}
