import Head from 'next/head'
import { tw, css } from 'twind/css'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (

    <div className={tw`flex flex-1 w-full h-full min-h-[100vh] flex-col ${css({ backgroundImage: "url('/images/back.svg')" })}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className={tw`flex w-full h-[10vh] backdrop-blur-md bg-white/30 items-center px-10 justify-between`}>
        <div className={tw`flex flex-row items-center space-x-4`}> <img src="/images/logo.svg" alt="logo baramo" />
          <p className={tw`font-medium text-xl text-black`}>BARAMO</p>
        </div>
        <div className={tw`flex flex-row items-center space-x-10 text-black`}>
          <div className={tw`cursor-pointer`}>WE ARE</div>
          <div className={tw`cursor-pointer`}>SERVICES</div>
          <div className={tw`cursor-pointer`}>CRÉATIONS</div>
          <div className={tw`cursor-pointer`}>ÉQUIPE</div>
          <div className={tw`text-[#9747FF] cursor-pointer`}>CONTACT</div>
        </div>

      </div>

      <div className={tw`flex w-full h-[90vh] px-10 text-9xl items-center text-black`}>
        <div className={tw`flex h-full items-end pb-10 `}> <img src="/images/scroll.svg" alt="barre de scroll" /> </div>
        <div className={tw`px-20 max-w-[60%]`}>
          <h1> WE BUILD</h1>
          <h1 className={tw`text-right`}> BETTER </h1>
          <h1 className={tw`text-[#9747FF]`}> EXPERIENCE </h1>
          <p className={tw`text-base text-gray-400 mt-8`}> Lorem ipsum dolor sit amet, consectetur adipiscing elit dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.  </p>

        </div>

        <div>
          <img src="/images/boule.svg" alt="" />
        </div>

      </div>

      <div className={tw`flex w-full h-[90vh] px-10 text-8xl items-center text-black`}>
        <div className={tw`px-20 max-w-[60%]`}>
          <h2>QUI SOMMES NOUS</h2>
          <p className={tw`text-base text-gray-400 mt-8`}> Lorem ipsum dolor sit amet, consectetur adipiscing elit dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.  </p>

        </div>
      </div>


    </div>
  )
}
